# Generated by Django 5.1.2 on 2024-12-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisoruser',
            name='advisor_name',
        ),
        migrations.RemoveField(
            model_name='advisoruser',
            name='email',
        ),
        migrations.AddField(
            model_name='advisoruser',
            name='role',
            field=models.CharField(default='default', max_length=256, verbose_name='Role'),
            preserve_default=False,
        ),
    ]
